media: public/assets/img
content:
  - name: home
    label: Home page
    path: content/_index.md
    type: file
    fields:
      - label: "Slider 1"
        name: "slider1"
        type: "object"
        fields:
          - { label: "Span", name: "span", type: "string" }
          - { label: "Text", name: "text", type: "string" }
          - { label: "Image", name: "image", type: "string" }
          - { label: "Youtube", name: "embed_youtube", type: "string" }

      - label: "Slider 2"
        name: "slider2"
        type: "object"
        fields:
          - { label: "Span", name: "span", type: "string" }
          - { label: "Text", name: "text", type: "string" }
          - { label: "Image", name: "image", type: "string" }
          - { label: "Youtube", name: "embed_youtube", type: "string" }

      - label: "Slider 3"
        name: "slider3"
        type: "object"
        fields:
          - { label: "Span", name: "span", type: "string" }
          - { label: "Text", name: "text", type: "string" }
          - { label: "Image", name: "image", type: "string" }
          - { label: "Youtube", name: "embed_youtube", type: "string" }

      - label: "Card 1"
        name: "card1"
        type: "object"
        fields:
          - { label: "Title", name: "title", type: "string" }
          - { label: "Text", name: "description", type: "string" }

      - label: "Card 2"
        name: "card2"
        type: "object"
        fields:
          - { label: "Title", name: "title", type: "string" }
          - { label: "Text", name: "description", type: "string" }

      - label: "Card 3"
        name: "card3"
        type: "object"
        fields:
          - { label: "Title", name: "title", type: "string" }
          - { label: "Text", name: "description", type: "string" }

      - label: "image Card"
        name: "imageCard"
        type: "object"
        fields:
          - { label: "Title", name: "title", type: "string" }
          - { label: "Text", name: "description", type: "string" }
          - { label: "Image", name: "image", type: "string" }

      - label: "welcome Span"
        name: "welcomeSpan"
        type: "object"
        fields:
          - { label: "span", name: "span", type: "string" }

      
      - label: "welcome Head 1"
        name: "welcomeHead1"
        type: "object"
        fields:
          - { label: "Title", name: "title", type: "string" }
          - { label: "Text", name: "description", type: "string" }

      - label: "welcome Head 2"
        name: "welcomeHead2"
        type: "object"
        fields:
          - { label: "Title", name: "title", type: "string" }
          - { label: "Text", name: "description", type: "string" } 
          
     

        
      
  - name: about
    label: About us
    path: content/about/_index.md
    type: file
    fields:
            - label: "about Area"
              name: "aboutArea"
              type: "object"
              fields:
                - { label: "Span", name: "span", type: "string" }
                - { label: "title", name: "title", type: "string" }
                - { label: "description", name: "description", type: "string" }
                - { label: "boxTitle", name: "boxTitle", type: "string" }
                - { label: "boxDescription", name: "boxDescription", type: "string" }
                - { label: "name", name: "name", type: "string" }
                - { label: "designation", name: "designation", type: "string" }


            - label: "services History"
              name: "servicesHistory"
              type: "object"
              fields:
                - { label: "service1year", name: "service1year", type: "string" }
                - { label: "service1title", name: "service1title", type: "string" }
                - { label: "service1explain", name: "service1explain", type: "string" }
                - { label: "service2year", name: "service2year", type: "string" }
                - { label: "service2title", name: "service2title", type: "string" }
                - { label: "service2explain", name: "service2explain", type: "string" }
                - { label: "service3year", name: "service3year", type: "string" }
                - { label: "service3title", name: "service3title", type: "string" }
                - { label: "service3explain", name: "service3explain", type: "string" }
                - { label: "service4year", name: "service4year", type: "string" }
                - { label: "service4title", name: "service4title", type: "string" }
                - { label: "service4explain", name: "service4explain", type: "string" } 
          



  - name: services
    label: Services
    path: content/services
    type: "collection"
    fields:
         - label: "Service Area"
           name: "serviceArea"
           type: "object"
           fields:
             - { label: "title", name: "title", type: "text" }

         
                
        
  - name: bio 
    label: "Bio"
    path: content/bio/_index.md
    type: file
    fields:

        - label: "Bio Area"
          name: "bioArea"
          type: "object"
          fields:
            - { label: "name", name: "name", type: "string" }
            - { label: "occupation", name: "occupation", type: "string" }
            - { label: "aboutYou", name: "aboutYou", type: "string" }
            - { label: "image", name: "image", type: "string" }


                
  - name: contact 
    label: Contact Us
    path: content/contact/_index.md
    type: file
    fields:
      
      - label: "contact Area "
        name: "contactArea"
        type: "object"
        fields:
          - { label: "description", name: "description", type: "string" }




  - name: config
    label: website config
    type: file
    path: hugo.toml
    fields:
      - {label: BaseUrl, name: baseurl, type: string, default: /}
      - {label: TabTitle, name: title, type: string}
      - name: params
        label: Generic Parameters
        type: object
        fields:
            - {label: Website, name: website, type: string}
            - {label: Experience, name: experience, type: string}
            - {label: Company, name: company, type: string}
            - {label: email, name: email, type: string}
            - {label: mobile, name: mobile, type: string}
            - {label: address, name: address, type: string}
            - {label: keywords(comma separated), name: keywords, type: string}
        


  
          
        
            
            


        
