media: public/assets/img
content:
  - name: home
    label: Home page
    path: content/_index.md
    type: file
    fields:
      - label: "Slider 1"
        name: "slider1"
        type: "object"
        fields:
          - { label: "Span", name: "span", type: "string" }
          - { label: "Text", name: "text", type: "string" }
          - { label: "Image", name: "image", type: "string" }
          - { label: "Youtube", name: "embed_youtube", type: "string" }

      - label: "Slider 2"
        name: "slider2"
        type: "object"
        fields:
          - { label: "Span", name: "span", type: "string" }
          - { label: "Text", name: "text", type: "string" }
          - { label: "Image", name: "image", type: "string" }
          - { label: "Youtube", name: "embed_youtube", type: "string" }

      - label: "Slider 3"
        name: "slider3"
        type: "object"
        fields:
          - { label: "Span", name: "span", type: "string" }
          - { label: "Text", name: "text", type: "string" }
          - { label: "Image", name: "image", type: "string" }
          - { label: "Youtube", name: "embed_youtube", type: "string" }

      - label: "Card 1"
        name: "card1"
        type: "object"
        fields:
          - { label: "Title", name: "title", type: "string" }
          - { label: "Text", name: "description", type: "string" }

      - label: "Card 2"
        name: "card2"
        type: "object"
        fields:
          - { label: "Title", name: "title", type: "string" }
          - { label: "Text", name: "description", type: "string" }

      - label: "Card 3"
        name: "card3"
        type: "object"
        fields:
          - { label: "Title", name: "title", type: "string" }
          - { label: "Text", name: "description", type: "string" }

      - label: "image Card"
        name: "imageCard"
        type: "object"
        fields:
          - { label: "Title", name: "title", type: "string" }
          - { label: "Text", name: "description", type: "string" }
          - { label: "Image", name: "image", type: "string" }

      - label: "welcome Span"
        name: "welcomeSpan"
        type: "object"
        fields:
          - { label: "span", name: "span", type: "string" }

      
      - label: "welcome Head 1"
        name: "welcomeHead1"
        type: "object"
        fields:
          - { label: "Title", name: "title", type: "string" }
          - { label: "Text", name: "description", type: "string" }

      - label: "welcome Head 2"
        name: "welcomeHead2"
        type: "object"
        fields:
          - { label: "Title", name: "title", type: "string" }
          - { label: "Text", name: "description", type: "string" } 
          
      - label: "welcome Head 3"
          name: "welcomeHead3"
          type: "object"
          fields:
            - { label: "Title", name: "title", type: "string" }
            - { label: "Text", name: "description", type: "string" } 

      - label: "Services Head"
          name: "servicesHead"
          type: "object"
          fields:
            - { label: "Title", name: "title", type: "string" }
            - { label: "Text", name: "description", type: "string" } 
            

      - label: "services Card 1"
          name: "servicesCard1"
          type: "object"
          fields:
            - { label: "Title", name: "title", type: "string" }
            - { label: "Text", name: "description", type: "string" } 
            - { label: "button", name: "button", type: "button" } 
      - label: "services Card 2"
          name: "servicesCard2"
          type: "object"
          fields:
            - { label: "Title", name: "title", type: "string" }
            - { label: "Text", name: "description", type: "string" } 
            - { label: "button", name: "button", type: "button" } 
      - label: "Services Card 3"
          name: "servicesCard3"
          type: "object"
          fields:
            - { label: "Title", name: "title", type: "string" }
            - { label: "Text", name: "description", type: "string" } 
            - { label: "button", name: "button", type: "button" } 
      - label: "Services Card 4"
          name: "servicesCard4"
          type: "object"
          fields:
            - { label: "Title", name: "title", type: "string" }
            - { label: "Text", name: "description", type: "string" } 
            - { label: "button", name: "button", type: "button" } 
      - label: "Services Card 5"
          name: "servicesCard5"
          type: "object"
          fields:
            - { label: "Title", name: "title", type: "string" }
            - { label: "Text", name: "description", type: "string" } 
            - { label: "button", name: "button", type: "button" } 
      - label: "Services Card 6"
          name: "servicesCard6"
          type: "object"
          fields:
            - { label: "Title", name: "title", type: "string" }
            - { label: "Text", name: "description", type: "string" } 
            - { label: "button", name: "button", type: "button" } 


      - label: "project Area"
          name: "projectArea"
          type: "object"
          fields:
            - { label: "Title", name: "title", type: "string" }
            - { label: "span", name: "span", type: "string" } 
           
      - label: "project Area 1"
          name: "projectArea1"
          type: "object"
          fields:
            - { label: "Title", name: "title", type: "string" }
            - { label: "span", name: "span", type: "string" } 
            - { label: "image", name: "image", type: "string" }  

        - label: "project Area 2"
          name: "projectArea1"
          type: "object"
          fields:
            - { label: "Title", name: "title", type: "string" }
            - { label: "span", name: "span", type: "string" } 
            - { label: "image", name: "image", type: "string" }  
      - label: "project Area 3"
          name: "projectArea3"
          type: "object"
          fields:
            - { label: "Title", name: "title", type: "string" }
            - { label: "span", name: "span", type: "string" } 
            - { label: "image", name: "image", type: "string" }   
        - label: "project Area 4"
          name: "projectArea4"
          type: "object"
          fields:
            - { label: "Title", name: "title", type: "string" }
            - { label: "span", name: "span", type: "string" } 
            - { label: "image", name: "image", type: "string" }  
      - label: "project Area 5"
          name: "projectArea5"
          type: "object"
          fields:
            - { label: "Title", name: "title", type: "string" }
            - { label: "span", name: "span", type: "string" }
            - { label: "image", name: "image", type: "string" }   

      - label: "team Area"
          name: "teamArea"
          type: "object"
          fields:
            - { label: "Title", name: "title", type: "string" }
            - { label: "span", name: "span", type: "string" }
      - label: "team Member 1"
          name: "teamMember1"
          type: "object"
          fields:
            - { label: "Title", name: "title", type: "string" }
            - { label: "span", name: "span", type: "string" }      
            - { label: "image", name: "image", type: "string" } 
            - { label: "Facebook", name: "facebook", type: "string" }
            - { label: "Twitter", name: "twitter", type: "string" }      
            - { label: "Pinterest", name: "pinterest", type: "string" } 
      - label: "team Member 2"
          name: "teamMember2"
          type: "object"
          fields:
            - { label: "Title", name: "title", type: "string" }
            - { label: "span", name: "span", type: "string" }      
            - { label: "image", name: "image", type: "string" } 
            - { label: "Facebook", name: "facebook", type: "string" }
            - { label: "Twitter", name: "twitter", type: "string" }      
            - { label: "Pinterest", name: "pinterest", type: "string" } 
      - label: "team Member 3"
          name: "teamMember3"
          type: "object"
          fields:
            - { label: "Title", name: "title", type: "string" }
            - { label: "span", name: "span", type: "string" }      
            - { label: "image", name: "image", type: "string" } 
            - { label: "Facebook", name: "facebook", type: "string" }
            - { label: "Twitter", name: "twitter", type: "string" }      
            - { label: "Pinterest", name: "pinterest", type: "string" } 

      - label: "counter Area 1"
          name: "counterArea1"
          type: "object"
          fields:
            - { label: "Numbers", name: "numbers", type: "integer" }
            - { label: "span", name: "span", type: "string" }  
      - label: "counter Area 2"
          name: "counterArea2"
          type: "object"
          fields:
           - { label: "Numbers", name: "numbers", type: "integer" }
            - { label: "span", name: "span", type: "string" }   
      - label: "counter Area 3"
          name: "counterArea3"
          type: "object"
          fields:
            - { label: "Numbers", name: "numbers", type: "integer" }
            - { label: "span", name: "span", type: "string" }  
      - label: "counter Area 4"
          name: "counterArea4"
          type: "object"
          fields:
            - { label: "Numbers", name: "numbers", type: "integer" }
            - { label: "span", name: "span", type: "string" }  

      - label: "why Choose Area"
          name: "whyChooseArea"
          type: "object"
          fields:
            - { label: "Title", name: "title", type: "string" }
            - { label: "span", name: "span", type: "string" }      
            - { label: "image", name: "image", type: "string" } 
            - { label: "List 1", name: "list1", type: "string" }
            - { label: "List 2", name: "list2", type: "string" }      
            - { label: "List 3", name: "list3", type: "string" } 
            - { label: "List 4", name: "list4", type: "string" }      
            - { label: "List 5", name: "list5", type: "string" } 

        - label: "Image Testimonial Area"
          name: "imageTestimonialArea"
          type: "object"
          fields:
            - { label: "image", name: "image", type: "string" }
            - { label: "headline", name: "headline", type: "string" }  

        - label: "Testimonial Feedback"
          name: "testimonialFeedback"
          type: "object"
          fields:
            - { label: "span", name: "span", type: "string" }
            - { label: "title", name: "title", type: "string" }  

        - label: "patient Feedback 1"
          name: "patientFeedback1"
          type: "object"
          fields:
            - { label: "description", name: "description", type: "string" }
            - { label: "image", name: "image", type: "string" } 
            - { label: "customer Name", name: "customerName", type: "string" }
            - { label: "location Name", name: "locationName", type: "string" } 
        - label: "patient Feedback 2"
          name: "patientFeedback2"
          type: "object"
          fields:
            - { label: "description", name: "description", type: "string" }
            - { label: "image", name: "image", type: "string" } 
            - { label: "customer Name", name: "customerName", type: "string" }
            - { label: "location Name", name: "locationName", type: "string" } 
        - label: "patient Feedback 3"
          name: "patientFeedback3"
          type: "object"
          fields:
            - { label: "description", name: "description", type: "string" }
            - { label: "image", name: "image", type: "string" } 
            - { label: "customer Name", name: "customerName", type: "string" }
            - { label: "location Name", name: "locationName", type: "string" } 

        - label: "contact Area"
          name: "contactArea"
          type: "object"
          fields:
            - { label: "span", name: "span", type: "string" }
            - { label: "headline", name: "headline", type: "string" } 






  - name: services
    label: Services
    path: content/services
    type: collection

  - name: config
    label: website config
    type: file
    path: hugo.toml
    fields:
      - {label: BaseUrl, name: baseurl, type: string, default: /}
      - {label: TabTitle, name: title, type: string}
      - name: params
        label: Generic Parameters
        type: object
        fields:
            - {label: Website, name: website, type: string}
            - {label: Experience, name: experience, type: string}
            - {label: Company, name: company, type: string}
            - {label: email, name: email, type: string}
            - {label: mobile, name: mobile, type: string}
            - {label: address, name: address, type: string}
            - {label: keywords(comma separated), name: keywords, type: string}
        


  - name: Contact 
    label: Contact Us
    path: content/contact
    type: file
    fields:
      - label: "breadcrumbs Image "
        name: "breadcrumbsImage"
        type: "object"
        fields:
          - { label: "list1", name: "list1", type: "string" }
          - { label: "list2", name: "list2", type: "string" }
          - { label: "Image", name: "image", type: "string" }

      - label: "contact Area "
        name: "contactArea"
        type: "object"
        fields:
          - { label: "span", name: "span", type: "string" }
          - { label: "title", name: "title", type: "string" }
          - { label: "description", name: "description", type: "string" }
          
      - label: "choose Problem "
        name: "chooseProblem"
        type: "object"
        fields:
          - { label: "list1", name: "list1", type: "string" }
          - { label: "list2", name: "list2", type: "string" }
          - { label: "list3", name: "list3", type: "string" }
          - { label: "list4", name: "list4", type: "string" }
          - { label: "list5", name: "list5", type: "string" }    
      
      - label: "address Card"
        name: "addressCard"
        type: "object"
        fields:
          - { label: "title", name: "title", type: "string" }
          - { label: "span", name: "span", type: "string" }
      
      - label: "contact Details"
        name: "contactDetails"
        type: "object"
        fields:
          - { label: "title", name: "title", type: "string" }
          - { label: "span", name: "span", type: "string" }
      
      - label: "email Details"
        name: "emailDetails"
        type: "object"
        fields:
          - { label: "email", name: "email", type: "string" }
          - { label: "span", name: "span", type: "string" }
      
      - label: " map Iframe "
        name: "mapIframe"
        type: "object"
        fields:
          - { label: "iframe", name: "iframe", type: "string" }
          

  - name: config
    label: website config
    type: file
    path: hugo.toml
    fields:
      - {label: BaseUrl, name: baseurl, type: string, default: /}
      - {label: TabTitle, name: title, type: string}
      - name: params
        label: Generic Parameters
        type: object
        fields:
            - {label: Website, name: website, type: string}
            - {label: Experience, name: experience, type: string}
            - {label: Company, name: company, type: string}
            - {label: email, name: email, type: string}
            - {label: mobile, name: mobile, type: string}
            - {label: address, name: address, type: string}
            - {label: keywords(comma separated), name: keywords, type: string}
        
